// frontend/src/app/components/control-hub.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
} from '@angular/core';
import { Toolbar, ToolbarWidget } from '@angular/aria/toolbar';
import { WorkspaceService } from '../core/workspace.service';
import { IngestionService } from '../core/ingestion.service';
import { AgentService } from '../core/agent.service';
import { BackendService } from '../core/backend.service';
import { TerminalComponent } from './terminal.component';

/**
 * Conversational Control Hub (PRD §3.1). The conversation surface is a real
 * terminal (xterm.js, fed the raw PTY stream — see TerminalComponent), so this
 * shell provides the session controls, the harness selector, the downstream
 * agent run output, and diagnostic readouts of the background connection. Ideas
 * land on the canvas, not here.
 */
@Component({
  selector: 'as-control-hub',
  imports: [Toolbar, ToolbarWidget, TerminalComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (workspaces.active(); as ws) {
      <header class="bar">
        <div class="diag">
          <span class="conn" [attr.data-state]="backend.state()"></span>
          <span>{{ backend.state() }}</span>
          <span class="sep">·</span>
          <span>{{ ws.status }}</span>
        </div>
        <div class="session" ngToolbar orientation="horizontal" aria-label="Session controls">
          @if (ingestion.isAttached(ws.id)) {
            <button ngToolbarWidget value="stop" class="stop" (click)="stop(ws.id)">Stop</button>
          } @else {
            <button ngToolbarWidget value="start" class="start" (click)="start(ws.id)">
              Start session
            </button>
          }
          <button ngToolbarWidget value="clear" class="ghost" (click)="ingestion.clearTerminal(ws.id)">
            Clear
          </button>
        </div>
      </header>

      <div class="config">
        <label>harness</label>
        <input
          class="harness"
          [value]="ws.terminal.agentCommand || 'claude'"
          [disabled]="ingestion.isAttached(ws.id)"
          placeholder="claude"
          spellcheck="false"
          (change)="setHarness(ws.id, $event)"
          title="The AI CLI launched for this workspace's session (PRD §2). Keystrokes are sent to its PTY."
        />
        <span class="hint">a real terminal — type directly; ideas land on the canvas</span>
      </div>

      <section class="terminal-wrap">
        @if (!ingestion.isAttached(ws.id)) {
          <div class="empty">No session yet. Start a session, then talk to the agent in the terminal; ideas land on the canvas.</div>
        }
        <as-terminal />
      </section>

      @if (agentRun(); as run) {
        <section class="agent">
          <div class="agent__head">
            <span>agent: {{ ws.terminal.agentCommand || 'claude' }}</span>
            <span class="agent__status" [attr.data-state]="run.status">
              {{ run.status }}{{ run.code !== undefined ? ' (' + run.code + ')' : '' }}
            </span>
          </div>
          @if (run.output) {
            <pre class="agent__out">{{ run.output }}</pre>
          }
        </section>
      }
    }
  `,
  styles: [
    `
      :host {
        display: flex;
        flex-direction: column;
        height: 100%;
        min-height: 0;
      }
      .bar {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: var(--space-3);
        border-bottom: 1px solid var(--border-strong);
        background: var(--panel-bg);
        box-shadow: var(--shadow-sm);
      }
      .diag {
        display: flex;
        align-items: center;
        gap: var(--space-2);
        font-size: 0.7rem;
        font-weight: 600;
        color: var(--text-dim);
        text-transform: uppercase;
        letter-spacing: 0.05em;
      }
      .conn {
        width: 8px;
        height: 8px;
        border-radius: 50%;
        background: var(--danger);
        box-shadow: 0 0 0 3px color-mix(in srgb, var(--danger) 22%, transparent);
        transition: box-shadow var(--dur) var(--ease-out);
      }
      .conn[data-state='open'] {
        background: var(--ok);
        box-shadow: 0 0 0 3px color-mix(in srgb, var(--ok) 22%, transparent);
      }
      .conn[data-state='connecting'] {
        background: var(--warn);
        box-shadow: 0 0 0 3px color-mix(in srgb, var(--warn) 22%, transparent);
        animation: pulse 1.4s var(--ease-out) infinite;
      }
      @keyframes pulse {
        50% {
          opacity: 0.45;
        }
      }
      .sep {
        opacity: 0.35;
      }
      .config {
        display: flex;
        align-items: center;
        gap: var(--space-2);
        padding: var(--space-2) var(--space-3);
        border-bottom: 1px solid var(--border);
        background: var(--sidebar-bg);
        font-size: 0.7rem;
        color: var(--text-faint);
      }
      .config label {
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.05em;
      }
      .harness {
        flex: 0 0 auto;
        width: 180px;
        border-radius: var(--radius-sm);
        border: 1px solid var(--border-strong);
        background: var(--input-bg);
        color: var(--text);
        padding: 0.3rem 0.55rem;
        font-family: var(--mono);
        font-size: 0.76rem;
        transition:
          border-color var(--dur-fast) var(--ease-out),
          box-shadow var(--dur-fast) var(--ease-out);
      }
      .harness:hover:not(:disabled) {
        border-color: var(--accent);
      }
      .harness:focus {
        outline: none;
        border-color: var(--accent);
        box-shadow: 0 0 0 3px var(--accent-ring);
      }
      .harness:disabled {
        opacity: 0.5;
      }
      .config .hint {
        opacity: 0.7;
        font-style: italic;
      }
      .session {
        display: flex;
        gap: var(--space-2);
      }
      .session button {
        border-radius: var(--radius-sm);
        padding: 0.36rem 0.75rem;
        cursor: pointer;
        font: inherit;
        font-size: 0.76rem;
        font-weight: 600;
        border: 1px solid var(--border-strong);
        background: var(--btn-bg);
        color: var(--text-dim);
        transition:
          background var(--dur-fast) var(--ease-out),
          color var(--dur-fast) var(--ease-out),
          border-color var(--dur-fast) var(--ease-out),
          transform var(--dur-fast) var(--ease-out);
      }
      .session button:hover {
        background: var(--btn-hover);
        color: var(--text);
      }
      .session button:active {
        transform: translateY(1px);
      }
      .session button:focus-visible {
        outline: none;
        box-shadow: 0 0 0 3px var(--accent-ring);
      }
      .session:focus,
      .session:focus-visible {
        outline: none;
      }
      .start {
        color: var(--ok) !important;
        border-color: color-mix(in srgb, var(--ok) 35%, var(--border-strong)) !important;
      }
      .start:hover {
        background: color-mix(in srgb, var(--ok) 14%, var(--btn-bg)) !important;
      }
      .stop {
        color: var(--danger) !important;
        border-color: color-mix(in srgb, var(--danger) 35%, var(--border-strong)) !important;
      }
      .stop:hover {
        background: color-mix(in srgb, var(--danger) 14%, var(--btn-bg)) !important;
      }
      .terminal-wrap {
        position: relative;
        flex: 1;
        min-height: 0;
        background: var(--bg);
      }
      .terminal-wrap as-terminal {
        display: block;
        height: 100%;
      }
      .empty {
        position: absolute;
        inset: 0;
        z-index: 1;
        display: flex;
        flex-direction: column;
        gap: var(--space-2);
        align-items: flex-start;
        justify-content: flex-start;
        color: var(--text-faint);
        font-family: var(--sans);
        font-size: 0.82rem;
        line-height: 1.5;
        padding: var(--space-3);
        pointer-events: none;
        background: var(--bg);
      }
      .empty::before {
        content: '~';
        font-family: var(--mono);
        font-size: 1.1rem;
        color: var(--accent);
        opacity: 0.7;
      }
      .agent {
        border-top: 1px solid var(--border-strong);
        max-height: 35%;
        overflow-y: auto;
        background: var(--sidebar-bg);
      }
      .agent__head {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 0.5rem var(--space-3);
        font-size: 0.7rem;
        font-weight: 600;
        letter-spacing: 0.03em;
        color: var(--text-dim);
        position: sticky;
        top: 0;
        background: var(--panel-bg);
        border-bottom: 1px solid var(--border);
      }
      .agent__status {
        text-transform: uppercase;
        letter-spacing: 0.05em;
        font-size: 0.66rem;
      }
      .agent__status[data-state='exit'] {
        color: var(--ok);
      }
      .agent__status[data-state='error'] {
        color: var(--danger);
      }
      .agent__status[data-state='running'] {
        color: var(--accent);
      }
      .agent__out {
        margin: 0;
        padding: var(--space-3);
        font-family: var(--mono);
        font-size: 0.74rem;
        line-height: 1.5;
        white-space: pre-wrap;
        word-break: break-word;
        color: var(--text);
      }
    `,
  ],
})
export class ControlHubComponent {
  readonly workspaces = inject(WorkspaceService);
  readonly ingestion = inject(IngestionService);
  readonly backend = inject(BackendService);
  readonly #agent = inject(AgentService);

  readonly agentRun = computed(() => {
    const id = this.workspaces.activeId();
    return id ? this.#agent.run(id)() : null;
  });

  constructor() {
    // Resume a durable session after a reload / hot-switch (PRD §3.5). A page
    // reload loses the client-side pipeline but the named backend session
    // survives, so on (re)activation we re-attach to it. We gate on the
    // *persisted* live status ('active' / 'streaming') as the proxy for "this
    // workspace had a session", so merely visiting a never-started workspace
    // does not spawn a harness. `attach` is idempotent: it reconnects to the
    // surviving session rather than respawning it.
    effect(() => {
      const ws = this.workspaces.active();
      if (!ws) return;
      const wasLive = ws.status === 'active' || ws.status === 'streaming';
      if (wasLive && !this.ingestion.isAttached(ws.id)) {
        this.ingestion.attach(ws.id, ws.terminal);
      }
    });
  }

  setHarness(id: string, event: Event): void {
    const value = (event.target as HTMLInputElement).value.trim();
    this.workspaces.patchTerminal(id, { agentCommand: value || 'claude' });
  }

  start(id: string): void {
    const ws = this.workspaces.active();
    if (ws) this.ingestion.attach(id, ws.terminal);
  }

  stop(id: string): void {
    // Explicit "Stop" tears the durable session down (PRD §5.2). A browser
    // refresh / socket drop only detaches and leaves the session alive (§3.5).
    this.ingestion.kill(id);
  }
}

// frontend/src/app/components/ControlHub.tsx
import { useEffect } from 'react'
import * as Toolbar from '@radix-ui/react-toolbar'
import { useWorkspaceStore, selectActive, workspace } from '../stores/workspace.store'
import { useIngestionStore, ingestion } from '../stores/ingestion.store'
import { useAgentStore } from '../stores/agent.store'
import { useBackendStore } from '../stores/backend.store'

/**
 * Conversational Control Hub (PRD §3.1). The conversation surface is a real
 * terminal (xterm.js, fed the raw PTY stream — see Terminal), so this shell
 * provides the session controls, the harness selector, the downstream agent run
 * output, and diagnostic readouts of the background connection. Ideas land on
 * the canvas, not here.
 */
import { Terminal } from './Terminal'

export function ControlHub() {
  const ws = useWorkspaceStore(selectActive)
  const connState = useBackendStore((s) => s.state)
  const attached = useIngestionStore((s) => (ws ? !!s.attached[ws.id] : false))
  const agentRun = useAgentStore((s) => (ws ? s.runs[ws.id] ?? null : null))

  // Resume a durable session after a reload / hot-switch (PRD §3.5). A page
  // reload loses the client-side pipeline but the named backend session
  // survives, so on (re)activation we re-attach to it. We gate on the persisted
  // live status ('active' / 'streaming') as the proxy for "this workspace had a
  // session", so merely visiting a never-started workspace does not spawn a
  // harness. `attach` is idempotent: it reconnects rather than respawning.
  useEffect(() => {
    if (!ws) return
    const wasLive = ws.status === 'active' || ws.status === 'streaming'
    if (wasLive && !ingestion.isAttached(ws.id)) {
      ingestion.attach(ws.id, ws.terminal)
    }
  }, [ws, attached])

  if (!ws) return null

  const harness = ws.terminal.agentCommand || 'claude'

  const setHarness = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value.trim()
    workspace.patchTerminal(ws.id, { agentCommand: value || 'claude' })
  }

  const sessionBtn =
    'rounded-md border border-border-strong bg-btn px-3 py-1.5 text-[0.76rem] font-semibold text-text-dim transition-colors hover:bg-btn-hover hover:text-text active:translate-y-px focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-accent-ring'

  return (
    <div className="flex h-full min-h-0 flex-col">
      <header className="flex items-center justify-between border-b border-border-strong bg-panel p-3 shadow-[var(--shadow-sm)]">
        <div className="flex items-center gap-2 text-[0.7rem] font-semibold uppercase tracking-[0.05em] text-text-dim">
          <span className="as-conn" data-state={connState} />
          <span>{connState}</span>
          <span className="opacity-35">·</span>
          <span>{ws.status}</span>
        </div>
        <Toolbar.Root
          className="flex gap-2 focus:outline-none"
          orientation="horizontal"
          aria-label="Session controls"
        >
          {attached ? (
            <Toolbar.Button
              className={`${sessionBtn} !border-[color-mix(in_srgb,var(--danger)_35%,var(--border-strong))] !text-danger hover:!bg-[color-mix(in_srgb,var(--danger)_14%,var(--btn-bg))]`}
              onClick={() => ingestion.kill(ws.id)}
            >
              Stop
            </Toolbar.Button>
          ) : (
            <Toolbar.Button
              className={`${sessionBtn} !border-[color-mix(in_srgb,var(--ok)_35%,var(--border-strong))] !text-ok hover:!bg-[color-mix(in_srgb,var(--ok)_14%,var(--btn-bg))]`}
              onClick={() => ingestion.attach(ws.id, ws.terminal)}
            >
              Start session
            </Toolbar.Button>
          )}
          <Toolbar.Button className={sessionBtn} onClick={() => ingestion.clearTerminal(ws.id)}>
            Clear
          </Toolbar.Button>
        </Toolbar.Root>
      </header>

      <div className="flex items-center gap-2 border-b border-border-base bg-sidebar px-3 py-2 text-[0.7rem] text-text-faint">
        <label className="font-semibold uppercase tracking-[0.05em]">harness</label>
        <input
          className="w-[180px] flex-none rounded-md border border-border-strong bg-input px-[0.55rem] py-[0.3rem] font-mono text-[0.76rem] text-text transition-colors hover:border-accent focus:border-accent focus:outline-none focus:ring-3 focus:ring-accent-ring disabled:opacity-50"
          defaultValue={harness}
          key={`${ws.id}:${harness}`}
          disabled={attached}
          placeholder="claude"
          spellCheck={false}
          onChange={setHarness}
          title="The AI CLI launched for this workspace's session (PRD §2). Keystrokes are sent to its PTY."
        />
        <span className="italic opacity-70">
          a real terminal — type directly; ideas land on the canvas
        </span>
      </div>

      <section className="relative min-h-0 flex-1 bg-bg">
        {!attached && (
          <div className="pointer-events-none absolute inset-0 z-[1] flex flex-col items-start gap-2 bg-bg p-3 font-sans text-[0.82rem] leading-relaxed text-text-faint before:font-mono before:text-[1.1rem] before:text-accent before:opacity-70 before:content-['~']">
            No session yet. Start a session, then talk to the agent in the terminal; ideas land
            on the canvas.
          </div>
        )}
        <div className="block h-full">
          <Terminal />
        </div>
      </section>

      {agentRun && (
        <section className="max-h-[35%] overflow-y-auto border-t border-border-strong bg-sidebar">
          <div className="sticky top-0 flex items-center justify-between border-b border-border-base bg-panel px-3 py-2 text-[0.7rem] font-semibold tracking-[0.03em] text-text-dim">
            <span>agent: {harness}</span>
            <span
              className="text-[0.66rem] uppercase tracking-[0.05em] data-[state=error]:text-danger data-[state=exit]:text-ok data-[state=running]:text-accent"
              data-state={agentRun.status}
            >
              {agentRun.status}
              {agentRun.code !== undefined ? ` (${agentRun.code})` : ''}
            </span>
          </div>
          {agentRun.output && (
            <pre className="m-0 whitespace-pre-wrap break-words p-3 font-mono text-[0.74rem] leading-relaxed text-text">
              {agentRun.output}
            </pre>
          )}
        </section>
      )}
    </div>
  )
}
